### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by AxelTLarsson** [AxelTLarsson/receptdatabasen-api#38]
## Resources

https://editor.freelogodesign.org
https://looka.com/editor/53899345

**Comment by richardbmx** [comment]
Hello, are you looking for a custom logo for your project?

**Comment by AxelTLarsson** [comment]
Hey, @richardbmx. Yes, I was thinking about doing a vector version of something like this:

<img width="111" alt="logo" src="https://user-images.githubusercontent.com/3481284/92305571-d4066100-ef88-11ea-9442-077a7fbb5018.png">
